version: "3.7"

services:
  postgres:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: "1234"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"
volumes:
  db_data:
